#pragma once

namespace Pressia {

	enum class PSMouseCode {

		//From glfw3.h
		PS_MOUSE_BUTTON_1 = 0,
		PS_MOUSE_BUTTON_2 = 1,
		PS_MOUSE_BUTTON_3 = 2,
		PS_MOUSE_BUTTON_4 = 3,
		PS_MOUSE_BUTTON_5 = 4,
		PS_MOUSE_BUTTON_6 = 5,
		PS_MOUSE_BUTTON_7 = 6,
		PS_MOUSE_BUTTON_8 = 7,
		PS_MOUSE_BUTTON_LAST = PS_MOUSE_BUTTON_8,
		PS_MOUSE_BUTTON_LEFT = PS_MOUSE_BUTTON_1,
		PS_MOUSE_BUTTON_RIGHT = PS_MOUSE_BUTTON_2,
		PS_MOUSE_BUTTON_MIDDLE = PS_MOUSE_BUTTON_3,

	};

}


